In [ ]:
! pip install densratio

In [30]:
! pip install --quiet numba-scipy

In [ ]:
! pip install --upgrade scipy numba

In [ ]:
! conda install --yes rvlib

In [1]:
# TODO

# 1.
# Make non-linear in such a way that you cannot extrapolate to unseen P(Y,X)

# 2. 
# Use importance estimation to extrapolate.

# 3. 
# Show that when H|Z vs Z|H, extrapolation fails even with importance estimation. 

# 4
# Make true model such that excluding variables should recover a model that is "robust" (P(X|H))

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%load_ext rpy2.ipython

In [3]:
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [10, 3]

In [4]:
def plot_dat(vars_):
    f, axes = plt.subplots(len(vars_), 1, sharex=True, figsize=(20, 10))

    for (H,title),ax in zip(vars_, axes):
        for i,h in zip(['A', 'B', 'C', 'D'], H):
            sns.distplot(h, label = i, ax=ax)
        ax.legend()
        ax.set_title(title)
        
    # plt.title(title)
    # plt.show()

In [5]:
import numpy as np
from scipy.stats import gamma
import seaborn as sns
from copy import deepcopy

# Y := f(H, W, X, Z, N_Y)
# Y := f(W, X, Z, N_Y)
def fn(h, v, z, w):
    val = -1*(h > np.mean(h))*w*h**2 + w*h + w*z + np.random.normal(0, 5, size = h.shape[0])
    return val/10


def generate_data(N, fn, hidden_cause = True, plot=False, hiddens = [(20,2)]*4, v_conds = [(250,5,5)]*4):
    # H is latent variable, distribution changes (not )
    H = [gamma.rvs(a, loc=b, scale=1, size=N) for a,b in hiddens]

    # V := f(H, N_X)
    V = [(1/(h))*c + np.random.gamma(a, b, size=N) for h,(c,a,b) in zip(H, v_conds)]


    if not hidden_cause:
        V,H = deepcopy(H), deepcopy(V)

    # Z = [gamma.rvs(int(np.random.normal(40, 10)), loc=0, scale=1, size=N) for h in H]
    # Z := f(N_Z) 
    Z = [gamma.rvs(2, loc=1, scale=3, size=N) for h in H]

    # W := f(N_W) -- TREATMENT
    W = [np.random.binomial(1, 0.5, size=N) for h in H]

    # Y:= fn(H, V, Z, W, N_Y)
    Y = [fn(H[idx], V[idx], Z[idx], W[idx]) for idx in range(4)]

    taus = [fn(h,v,z,1) - fn(h,v,z,0) for h,v,z in zip(H,V,Z)]
    
    if plot:
        plot_dat([(H,'H'), (V, 'V') , (Z, 'Z'), (Y, 'Y'), (taus, 'tau')])

    return [(y, np.array([w,v,z]).T, tau) for y,v,z,w,h,tau in zip(Y, V, Z, W, H, taus)]

In [6]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.neighbors.kde import KernelDensity
from scipy.stats import gaussian_kde
from scipy.stats import wasserstein_distance
from itertools import combinations

def kde_score(X):
    return gaussian_kde(X).evaluate

def score_wasserstein(dat, phi, model, train_idx):
    y_train, X_train, _ = dat[train_idx]
    model.fit(phi(X_train), y_train)
    resids = [model.predict(phi(x)) - y for y,x,_ in dat]
    dists = [wasserstein_distance(resids[0], r) for r in resids]
    mss = [np.mean(r**2) for r in resids]
    score = np.sum(dists)
    return score


def filter_dat(d, idxs):
    return [(y, x[:,idxs],tau) for y,x,tau in d]

def search_wasserstein(dat, phi, model, train_idx):
    s = dat[0][1].shape[1]

    combs = [j for i in range(1,s) 
             for j in combinations(range(1, s), i)]

    combs = [[0] + list(c) for c in combs]

    scores = [score_wasserstein(filter_dat(dat, i), phi, model, train_idx) for i in combs]

    return combs[np.argmin(scores)]


def run_model(dat, model, phi, train_idx, target_idx, use_weights = None, model_search = False):
    X_train, X_target = dat[train_idx][1], dat[target_idx][1]

    if model_search:
        # exclude the target in the model search
        dd = [d for i,d in enumerate(dat) if i != target_idx]
        idxs = search_wasserstein(dd, phi, model, train_idx)
        # print('Choosing variables: ', idxs)
    else:
        idxs = range(0, X_train.shape[1])


    if use_weights is not None:
        ps, pt = kde_score(X_train[:, use_weights]), kde_score(X_target[:, use_weights])
        weights = pt(X_train[:, use_weights]) / ps(X_train[:, use_weights])
    else:
        weights = np.ones(X_train.shape[0])


    d = [(phi(x[:, idxs]), x[:, 0], y) for y,x,tau in dat]

    model.fit(d[train_idx][0], d[train_idx][2], sample_weight=weights)

    y0 = [np.mean(model.predict(p[w == 0])) for p,w,y in d]
    y1 = [np.mean(model.predict(p[w == 1])) for p,w,y in d]

    pred_ates = [a-b for a,b in zip(y1, y0)]
    _, _, true_ates = zip(*dat)

    return [np.round(np.abs(p-np.mean(t)), 4) for p,t in zip(pred_ates, true_ates)]

phi = PolynomialFeatures(degree=2, include_bias=False).fit_transform

In [7]:
hiddens = [(25, 2), (4, 15), (4, 20), (2, 25)]
# hiddens = [(10,2)]*4
v_conds = [(500,2,2)]*4
# v_conds = [(250,2,30), (250,5,10), (500,15,5), (500,40,2)]

dat = generate_data(2000,
                    fn, 
                    hidden_cause = False, 
                    plot = False, 
                    hiddens = hiddens,
                    v_conds = v_conds)

y, X, tau = dat[0]

In [8]:
from trees import TransferTreeRegressor, build_tree, Node
from criteria import mse, transfer, causal_tree_criterion

In [9]:
weights = np.random.exponential(scale = 4.0, size = y.shape[0])

weights = np.ones(y.shape[0])

In [10]:
ys, Xs, taus = zip(*dat)

ys_source, Xs_source = np.concatenate(ys[:-1]), np.concatenate(Xs[:-1])
ys_target, Xs_target = ys[-1], Xs[-1]

phi_source = phi(Xs_source[:, 1:])
phi_target = phi(Xs_target[:, 1:])

treatment = Xs_source[:, 0]
N = ys[0].shape[0]
context_idxs = np.array([j for i,_ in enumerate(ys[:-1]) for j in [i]*N])

In [ ]:
model = TransferTreeRegressor(criterion = transfer, max_depth = 5, min_samples_leaf = 10)

model.fit(phi_source, ys_source, treatment=treatment, context_idxs=context_idxs, target_X=phi_target)

In [ ]:
preds = [model.predict(phi(x[:, 1:])) for x in Xs]
[np.mean((p-t)**2) for p,t in zip(preds, taus)]

In [ ]:
np.mean((np.mean(taus[:-1]) - taus[-1])**2)

In [ ]:
[np.mean((np.mean(t) - t)**2) for t in taus]

# Causal Tree Test

In [11]:
from sklearn.model_selection import ParameterGrid
from copy import deepcopy

def make_nested_grid(params):
    return ParameterGrid({ key: list(ParameterGrid(value))
                           for key, value in params.items()})


def _crossval_score(model, X, y, treatment, weights, splitter, fit_params, init_params):
    model = deepcopy(model)
    model.set_params(**init_params)
    scores = []

    for train_idx, test_idx in splitter.split(X, treatment):
        model.fit(X[train_idx, :], 
                  y[train_idx], 
                  treatment = treatment[train_idx], 
                  sample_weight = weights[train_idx],
                  **fit_params)

        score = model.score(X[test_idx, :],
                            y[test_idx], 
                            treatment = treatment[test_idx], 
                            sample_weight = weights[test_idx],
                            **fit_params)
            
        scores.append(score)
    
    return np.mean(scores)

from joblib import Parallel, delayed

def model_search(model, X, y, treatment, weights, init_params, fit_params, splitter, n_jobs = -1):
    grid = make_nested_grid({'fit_params': fit_params, 
                             'init_params': init_params})

    all_scores = Parallel(n_jobs=n_jobs)(delayed(_crossval_score)(model, X, y, treatment, weights, splitter, **g) for g in grid)
    # all_scores = [_crossval_score(model, X, y, treatment, weights, splitter, **g) for g in grid]

    return list(zip(grid, all_scores))   

In [12]:
import pandas as pd


def get_simulation(fi = 'simulation-1-athey.csv'):
    df = pd.read_csv(fi)
    X = df.iloc[:, :4].values
    y = df.y.values
    treatment = df.treatment.values
    return X, y, treatment

sim_X, sim_y, sim_treatment = get_simulation()

In [13]:
def eta(X):
    return 0.5 * X[:, 0] + X[:, 1]

def kappa(X):
    return 0.5 * X[:, 0]

def gen_y(X, w):
    return eta(X) + 0.5 * (2*w - 1) * kappa(X) + np.random.normal(0, 0.01)

N = 1000
S = round(N/2)
X = np.random.normal(0, 1, (N, 6))
treatment = np.random.binomial(1, 0.5, N)
y = gen_y(X, treatment)

In [62]:
def eta(X):
    return 0.5 * np.sum(X[:, :2], axis=1) + np.sum(X[:, 2:], axis=1)

def kappa(X):
    return np.sum(X[:, :2] * (X[:, :2] > 0).astype(int), axis=1)

def gen_y(X, w):
    return eta(X) + 0.5 * (2*w - 1) * kappa(X) + np.random.normal(0, 0.01, size = X.shape[0])


N = 12000
S = 2000
X = np.random.normal(0, 1, (N, 6))
treatment = np.random.binomial(1, 0.5, N)
weights = np.ones(N)
y = gen_y(X, treatment)

In [63]:
sim_dat = pd.concat([pd.DataFrame(X, columns = range(1, 7)), 
                     pd.DataFrame({ 'y': y, 'treatment': treatment, 'tau': kappa(X)})], axis=1)

sim_dat.to_csv('sim_dat-2.csv', index=False)

In [64]:
# idx = np.arange(X.shape[0])
# np.random.shuffle(idx)

# treatment = treatment[idx]
# X = X[idx, :]
# y = y[idx]

In [65]:
%%time

from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold(n_splits = 3)

model = TransferTreeRegressor(criterion = causal_tree_criterion, 
                              min_samples_leaf = 4,
                              alpha = 0.1, 
                              honest = False)

fit_params = {'min_samples': [25] }
init_params = {'alpha': [ -.1, -0.05, -0.01, 0.0, 0.01, 0.05, 0.1, 0.4 ], 'honest': [True] }

results = model_search(model, X[:S], y[:S], treatment[:S], weights[:S], init_params, fit_params, cv)

best_params = sorted(results, key = lambda t: t[1])[0][0]['init_params']

best_params

CPU times: user 90.3 ms, sys: 27.6 ms, total: 118 ms
Wall time: 15.9 s


{'alpha': -0.01, 'honest': True}

In [101]:
from sklearn.metrics import r2_score

model = TransferTreeRegressor(criterion = causal_tree_criterion, 
                              min_samples_leaf = 4,
                              alpha = 0.1, 
                              honest = False)

# model.set_params(**best_params)
model.set_params(alpha = 0.0, honest=True)

model.fit(X[:S], y[:S], treatment=treatment[:S], min_samples=25, var_weight = 0.5)

print(r2_score(kappa(X[S:]), model.predict(X[S:])))

model.tree

0.41312961688576955


|--dim: 0, thresh: 0.9748, score: -0.1898, gain: 0.2114, tot_gain: 0.3160 
   |--dim: 3, thresh: -0.2668, score: -0.0293, gain: 0.0499, tot_gain: 0.1045 
      |--dim: 1, thresh: 0.2870, score: 0.0001, gain: 0.0097, tot_gain: 0.0174 
         |--pred: 0.0246, score: 0.0126, N: 202 
         |--dim: 4, thresh: 0.1007, score: -0.0222, gain: 0.0077, tot_gain: 0.0077 
            |--pred: 1.0202, score: -0.0227, N: 66 
            |--pred: 0.8655, score: -0.0072, N: 56 
      |--dim: 4, thresh: -0.9703, score: -0.0793, gain: -0.0133, tot_gain: 0.0373 
         |--pred: 0.3458, score: 0.0057, N: 81 
         |--dim: 1, thresh: -0.2146, score: -0.0716, gain: 0.0302, tot_gain: 0.0506 
            |--dim: 2, thresh: 0.6212, score: 0.0126, gain: 0.0127, tot_gain: 0.0127 
               |--pred: 0.4813, score: -0.0062, N: 154 
               |--pred: -0.4445, score: 0.0061, N: 48 
            |--dim: 5, thresh: 0.4866, score: -0.1144, gain: 0.0078, tot_gain: 0.0078 
               |--pred: 1.242

In [102]:
preds = pd.DataFrame(model.predict(X[S:], interval = 0.975), columns = ['pred', 'lower', 'upper'])

preds.assign(true = kappa(X[S:])) \
    .groupby('pred') \
    .apply(lambda df: df.assign(true_cate = df.true.mean())) \
    .pipe(lambda df: df.assign(within_int = (df.true_cate <= df.upper) & (df.true_cate >= df.lower))) \
    .pipe(lambda df: df['within_int'].sum() / df.shape[0])

1.0

In [86]:
xx = X[:S]
yy = y[:S]
ii = xx[:, 0] > 0.9748
tt = treatment[:S][ii]
np.var(yy[ii][tt == 0]), np.var(yy[ii][tt == 1])

(3.7992301635322527, 4.139212326977113)

In [ ]:
model = TransferTreeRegressor(criterion = mse, max_depth = 5, min_samples_leaf = 10)

model.fit(phi(X), y, sample_weight = weights)
preds = model.predict(phi(X))
# np.mean((preds - y)**2)

np.histogram(preds)

(array([  15,    0,   41,   23,   95,   47,   87,  103,  406, 1183]),
 array([-129.40835129, -116.21549089, -103.02263049,  -89.82977009,
         -76.63690969,  -63.44404929,  -50.25118889,  -37.05832849,
         -23.86546809,  -10.67260769,    2.52025272]))

In [60]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(max_depth=5, min_samples_leaf=10)

model.fit(phi(X), y, sample_weight = weights)
preds = model.predict(phi(X))
np.mean((preds - y)**2)

(array([  15,    0,   41,   23,   95,   47,   87,  103,  406, 1183]),
 array([-129.40835129, -116.21549089, -103.02263049,  -89.82977009,
         -76.63690969,  -63.44404929,  -50.25118889,  -37.05832849,
         -23.86546809,  -10.67260769,    2.52025272]))

In [34]:
model = DecisionTreeRegressor(max_depth=4, min_samples_leaf=20)

np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = None, model_search = True) for i in range(10)]), 0)

array([ 0.3661, 20.3762,  0.4404,  7.6768])

In [35]:
np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = None, model_search = False) for i in range(10)]), 0)

array([ 0.3656, 41.3072, 15.5   ,  1.5563])

In [36]:
np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = 1, model_search = True) for i in range(10)]), 0)

array([11.7473, 32.487 , 11.613 ,  4.5725])

In [37]:
np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = 1, model_search = False) for i in range(10)]), 0)

array([12.42759, 25.75614,  5.67631,  3.50874])

In [38]:
model = TransferTreeRegressor(criterion=mse, max_depth=4, min_samples_leaf=20)

np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = None, model_search = True) for i in range(10)]), 0)

array([ 0.3661, 20.3762,  0.4404,  7.6768])

In [39]:
np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = None, model_search = False) for i in range(10)]), 0)

array([ 0.3656, 41.3072, 15.5   ,  1.5563])

In [52]:
np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = 1, model_search = True) for i in range(10)]), 0)

array([11.3818, 32.1958, 11.2033,  3.5604])

In [51]:
np.mean(np.array([run_model(dat, model, phi, 0, 3, use_weights = 1, model_search = False) for i in range(10)]), 0)

array([10.9098,  4.9235,  3.2745,  3.7268])

In [42]:
model = LinearRegression(fit_intercept=False)
run_model(dat, model, phi, 0, 1, use_weights = None, model_search = False)

[0.3605, 21.2762, 16.201, 7.1304]

In [31]:
run_model(dat, model, phi, 0, 3, use_weights = None, model_search = True)

[0.4141, 20.8479, 0.2354, 6.2956]

In [32]:
run_model(dat, model, phi, 0, 1, use_weights = 1, model_search = False)

[12.3876, 41.752, 16.8672, 4.4122]

In [33]:
run_model(dat, model, phi, 0, 3, use_weights = 1, model_search = True)

[11.362, 31.8239, 11.2857, 4.7136]

In [1802]:
# get residuals for "sets" separately
# compute distance between residuals
# optimize squared errors + penalty for residual distance

# search for "sets" by looking at residuals and fitting a mixture model
# then optimize to remove that mixture...

# set up an adversarial problem: the adversary tries to find a 
# mixture model in your reiduals, the classifier tries to make force the
# adversary to fit a 1-component mixture, for example... 